### ISSUE TITLE
create listener rule instead of listener

### ISSUE THREAD

**Issue by sblack4** [rhythmictech/terraform-aws-alb-ecs-task#8]
https://github.com/rhythmictech/terraform-aws-alb-ecs-task/blob/d1400abdf4baa2ec662e511cfc62cff706b7a829/main.tf#L64

One listener typically listens on port 443 which then forwards to different target groups based on conditions like host headers. Refactor so that one listener can be created outside the module and then multible alb-ecs tasks can use it.

**Comment by smiller171** [comment]
hmm...Are we sure this is the approach we want to take?

I feel like logically it would make more sense to pass rules into the module than out of the module. If we really don't want to create the listener in the module, what advantage do we gain from creating rules in the module?

**Comment by sblack4** [comment]
Yes. This approach has the advantage of being able to create a single listener that listens on 443 and routes requests to different ECS services depending on their host header like you'll see if you review my OF PR

**Comment by smiller171** [comment]
Wouldn't you be able to do the same by passing a list of route objects into the module and using a for loop?

**Comment by smiller171** [comment]
oh, my brain had the entirely wrong context in mind

**Comment by smiller171** [comment]
This module is designed to create a single task. Now that I think about it that way, your approach makes total sense.
